export const data = [
  {
    'id': 'some_unique_gig_id',
    'account': 'some_account_unique_id',
    'employer': 'uber',
    'created_at': '2024-08-28T16:50:47.430Z',
    'updated_at': '2024-08-28T16:50:47.430Z',
    'status': 'completed',
    'type': 'rideshare',
    'task_count': 1,
    'start_datetime': '2024-6-04T05:19:55Z',
    'end_datetime': '2024-6-04T05:37:57Z',
    'all_datetimes': {
      'request_at': '2024-6-04T05:19:55Z',
      'accept_at': null,
      'pickup_at': null,
      'dropoff_at': null,
      'cancel_at': null,
      'shift_start': null,
      'shift_end': null,
      'breaks': [],
    },
    'duration': 1082,
    'timezone': 'America/Los_Angeles',
    'earning_type': 'work',
    'start_location': {
      'lat': 'some_latitude',
      'lng': 'some_longitude',
      'formatted_address': 'Street Address City, State Zip code',
    },
    'end_location': {
      'lat': 'some_latitude',
      'lng': 'some_longitude',
      'formatted_address': 'Street Addres City, State Zip code',
    },
    'distance': 'some_distance',
    'distance_unit': 'miles',
    'metadata': {
      'income': {
        'fees': [
          { 'name': 'Paid to third parties: Other expenses such as commercial auto insurance***', 'value': null },
          { 'name': 'Paid to third parties: Region or City Fee', 'value': null },
          { 'name': 'Paid to third parties: Driver Paid Sick Time', 'value': null },
          { 'name': 'Paid to third parties: Seattle Transportation Network Company Tax', 'value': null },
        ],
      },
      'origin_id': 'unique_id',
    },
    'circumstances': {
      'is_pool': false,
      'is_rush': null,
      'is_surge': true,
      'service_type': 'UberX',
      'position': null,
    },
    'income': {
      'currency': 'USD',
      'total_charge': '15.87',
      'fees': '6.09',
      'total': '7.12',
      'pay': '4.60',
      'tips': null,
      'bonus': '3.85',
      'other': null,
      'customer_price': '17.89',
    },
    'income_rates': { 'hour': null, 'mile': null },
    'task_details': {
      'events': [
        {
          'order_id': null,
          'sequence': '1',
          'type': 'pickup',
          'name': null,
          'formatted_address': 'pick up address',
          'lat': 'some_lat',
          'lng': 'some_long',
          'datetime': null,
        },
        {
          'order_id': null,
          'sequence': '2',
          'type': 'dropoff',
          'name': null,
          'formatted_address': 'drop off address',
          'lat': 'some_lat',
          'lng': 'some_long',
          'datetime': null,
        },
      ],
      'orders': [],
    },
  },
  {
    'id': 'another_unique_gig_id',
    'account': 'another_account_unique_id',
    'employer': 'lyft',
    'created_at': '2024-07-15T10:24:47.123Z',
    'updated_at': '2024-07-15T10:24:47.123Z',
    'status': 'cancelled',
    'type': 'rideshare',
    'task_count': 1,
    'start_datetime': '2024-7-15T07:30:55Z',
    'end_datetime': '2024-7-15T07:45:57Z',
    'all_datetimes': {
      'request_at': '2024-7-15T07:30:55Z',
      'accept_at': '2024-7-15T07:35:55Z',
      'pickup_at': null,
      'dropoff_at': null,
      'cancel_at': '2024-7-15T07:40:55Z',
      'shift_start': null,
      'shift_end': null,
      'breaks': [],
    },
    'duration': 900,
    'timezone': 'America/New_York',
    'earning_type': 'work',
    'start_location': {
      'lat': 'another_latitude',
      'lng': 'another_longitude',
      'formatted_address': 'Another Street Address City, State Zip code',
    },
    'end_location': {
      'lat': 'another_latitude',
      'lng': 'another_longitude',
      'formatted_address': 'Another Street Addres City, State Zip code',
    },
    'distance': 'another_distance',
    'distance_unit': 'miles',
    'metadata': {
      'income': {
        'fees': [
          { 'name': 'Paid to third parties: Other expenses such as commercial auto insurance***', 'value': null },
          { 'name': 'Paid to third parties: Region or City Fee', 'value': null },
          { 'name': 'Paid to third parties: Driver Paid Sick Time', 'value': null },
          { 'name': 'Paid to third parties: State Tax', 'value': null },
        ],
      },
      'origin_id': 'another_unique_id',
    },
    'circumstances': {
      'is_pool': false,
      'is_rush': true,
      'is_surge': false,
      'service_type': 'LyftX',
      'position': null,
    },
    'income': {
      'currency': 'USD',
      'total_charge': '10.50',
      'fees': '3.00',
      'total': '7.50',
      'pay': '5.50',
      'tips': '2.00',
      'bonus': null,
      'other': null,
      'customer_price': '12.50',
    },
    'income_rates': { 'hour': null, 'mile': null },
    'task_details': {
      'events': [
        {
          'order_id': null,
          'sequence': '1',
          'type': 'pickup',
          'name': null,
          'formatted_address': 'pick up address',
          'lat': 'another_lat',
          'lng': 'another_long',
          'datetime': null,
        },
        {
          'order_id': null,
          'sequence': '2',
          'type': 'dropoff',
          'name': null,
          'formatted_address': 'drop off address',
          'lat': 'another_lat',
          'lng': 'another_long',
          'datetime': null,
        },
      ],
      'orders': [],
    },
  },
  {
    'id': 'third_unique_gig_id',
    'account': 'third_account_unique_id',
    'employer': 'uber',
    'created_at': '2024-09-01T12:00:00.000Z',
    'updated_at': '2024-09-01T12:00:00.000Z',
    'status': 'completed',
    'type': 'rideshare',
    'task_count': 2,
    'start_datetime': '2024-09-01T12:00:00Z',
    'end_datetime': '2024-09-01T12:30:00Z',
    'all_datetimes': {
      'request_at': '2024-09-01T12:00:00Z',
      'accept_at': '2024-09-01T12:05:00Z',
      'pickup_at': '2024-09-01T12:10:00Z',
      'dropoff_at': '2024-09-01T12:25:00Z',
      'cancel_at': null,
      'shift_start': null,
      'shift_end': null,
      'breaks': [],
    },
    'duration': 1800,
    'timezone': 'America/Chicago',
    'earning_type': 'work',
    'start_location': {
      'lat': 'third_latitude',
      'lng': 'third_longitude',
      'formatted_address': 'Third Street Address City, State Zip code',
    },
    'end_location': {
      'lat': 'third_latitude',
      'lng': 'third_longitude',
      'formatted_address': 'Third Street Address City, State Zip code',
    },
    'distance': '8.5',
    'distance_unit': 'miles',
    'metadata': {
      'income': {
        'fees': [
          { 'name': 'Paid to third parties: Commercial auto insurance***', 'value': null },
          { 'name': 'Paid to third parties: City Fee', 'value': null },
          { 'name': 'Paid to third parties: Driver Paid Sick Time', 'value': null },
          { 'name': 'Paid to third parties: Local Tax', 'value': null },
        ],
      },
      'origin_id': 'third_unique_id',
    },
    'circumstances': {
      'is_pool': true,
      'is_rush': false,
      'is_surge': true,
      'service_type': 'UberPool',
      'position': null,
    },
    'income': {
      'currency': 'USD',
      'total_charge': '20.00',
      'fees': '7.50',
      'total': '12.50',
      'pay': '10.00',
      'tips': '1.50',
      'bonus': null,
      'other': null,
      'customer_price': '22.00',
    },
    'income_rates': { 'hour': null, 'mile': null },
    'task_details': {
      'events': [
        {
          'order_id': null,
          'sequence': '1',
          'type': 'pickup',
          'name': null,
          'formatted_address': 'pickup address',
          'lat': 'third_lat',
          'lng': 'third_long',
          'datetime': '2024-09-01T12:10:00Z',
        },
        {
          'order_id': null,
          'sequence': '2',
          'type': 'dropoff',
          'name': null,
          'formatted_address': 'dropoff address',
          'lat': 'third_lat',
          'lng': 'third_long',
          'datetime': '2024-09-01T12:25:00Z',
        },
      ],
      'orders': [],
    },
  },
];
